name: graph
channels:
  - pytorch
  - pyg
  - conda-forge
  - defaults
dependencies:
  - numcodecs
  - pandas
  - pip
  - pyg
  - python=3.11
  - pytorch
  - pytorch-cluster
  - pytorch-scatter
  - pytorch-sparse
  - pytorch-spline-conv
  - scikit-learn
  - scipy
  - torchvision
  - tqdm
  - xarray
  - zarr
  - h3-py
  - numpy
  - torch==2.2.2+cpu -f https://download.pytorch.org/whl/torch_stable.html
  - pip:
      - datasets
      - einops
      - fsspec
      - torch-geometric-temporal
      - huggingface-hub
      - pysolar
      - pytorch-lightning
      - click

      
