input:
  variables:
    training:
      basedir: /data2/malexe/weatherbench/netcdf/training
      filename-template: "pl_*.nc"
    validation:
      basedir: /data2/malexe/weatherbench/netcdf/validation
      filename-template: "pl_*.nc"
    names:
      - z
      - t
      - q
      - w
      - u
      - w
  constants:
    filename: /data2/malexe/weatherbench/netcdf/constants.nc
    names:
      - lsm
      - z_std

###################
#  OUTPUT BLOCK
###################
output:
  basedir: /data2/malexe/scratch/GNN/WeatherBench/checkpoints
  logging:
    log-dir: /data2/malexe/scratch/GNN/WeatherBench/logs
    log-interval: 25
  model:
    save-top-k: 3
    checkpoint-filename: "gnn-wb-weights-{epoch:02d}-{mse_train:.3f}"

model:
  debug:
    anomaly-detection: False
  wandb:
    enabled: False
  tensorboard:
    enabled: False
  dask:
    enabled: True
    temp-dir: /data2/malexe/scratch/GNN/WeatherBench/dask-tmp
    trim-worker-memory: True
    num-workers: 16
    num-threads-per-worker: 2
    persist-data: False
    dashboard-port: 9988
  dataloader:
    num-workers: 8
    batch-size: 1
    batch-chunk-size: 1
  # miscellaneous
  precision: 16
  fast-dev-run: False
  limit-train-batches: 1.0
  # specific GNN model settings
  lead-time: 6
  max-epochs: 1
  learn-rate: 2.e-3
  hidden-dim: 64
  num-blocks: 3
